// Generated by scripts/generate-sitemap.py. Do not edit by hand.
export const ORIGIN = "https://epdfconverter.com";

export const PAGES = [
  { path: "/", lastmod: "2026-09-11", changefreq: "weekly", priority: "1.0" },
  { path: "/compress-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/pdf-to-jpg", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/jpg-to-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/merge-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/image-compressor", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.9" },
  { path: "/image-resizer", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.9" },
  { path: "/resize-image", lastmod: "2026-09-11", changefreq: "monthly", priority: "0.8" },
  { path: "/edit-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/sign-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/unlock-protect-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/organise-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.8" },
  { path: "/privacy-policy", lastmod: "2026-09-10", changefreq: "yearly", priority: "0.3" },
  { path: "/terms", lastmod: "2026-09-10", changefreq: "yearly", priority: "0.3" },
  { path: "/about", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.4" },
  { path: "/contact", lastmod: "2026-09-10", changefreq: "yearly", priority: "0.3" },
  { path: "/blog", lastmod: "2026-09-10", changefreq: "weekly", priority: "0.7" },
  { path: "/blog-compress-pdf-for-email", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-merge-pdf-online", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-organise-pdf-pages", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-pdf-to-jpg", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-jpg-to-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-sign-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-edit-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-unlock-protect-pdf", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-compress-images", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-resize-images", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-photo-resize-ssc-upsc", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" },
  { path: "/blog-best-free-pdf-tools", lastmod: "2026-09-10", changefreq: "monthly", priority: "0.6" }
];
